name: Deploy static content docs to Pages

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Generate Rust Documentation
        run: cargo doc --no-deps

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.8'
      - name: Create mdBook Source Directory
        run: mkdir -p book/src/
      - name: Copy Rustdocs to mdBook Source
        run: cp -r ./target/doc/ ./book/src/

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
          publish_dir: ./book/html/