name: Deploy static content docs to Pages

on:
  push:
    branches: ["main"]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, rust-src

      - name: Build Documentation
        run: cargo doc --workspace --no-deps
        env:
          RUSTDOCFLAGS: -D warnings

      - name: Copy Rust Documentation to Zola
        run: cp -R "target/doc/" "docs/website/static/rustdocs/"

      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: docs/website/
          TOKEN: ${{ secrets.GH_PAGES_DEPLOY_KEY }}